import { MachineData } from './MachineCard';

// Sample machine data that matches the sample exactly
export const machines: MachineData[] = [
  {
    id: 'M001',
    name: 'Injection Molding #1',
    site: 'Site A',
    line: 'Line 1',
    status: 'Running',
    utilization: 87,
    utilizationTrend: 'up',
    cycleTime: 12.3,
    cycleTimeDelta: -0.4,
    shotCount: 1245,
    condition: 'High Speed Cycle',
    mold: 'M-2024-001',
    pinned: true,
    lastAlarm: 'Safety door open',
    alarmTime: '12m ago',
    dataAge: 2.1,
    setpointsChanged: true
  },
  {
    id: 'M002', 
    name: 'Injection Molding #2',
    site: 'Site A',
    line: 'Line 1',
    status: 'Idle',
    utilization: 65,
    utilizationTrend: 'down',
    cycleTime: 14.7,
    cycleTimeDelta: 0.8,
    shotCount: 892,
    condition: 'Standard Cycle',
    mold: 'M-2024-003',
    pinned: false,
    lastAlarm: 'Temperature warning',
    alarmTime: '1h ago',
    dataAge: 3.2,
    setpointsChanged: false
  },
  {
    id: 'M003',
    name: 'Injection Molding #3', 
    site: 'Site A',
    line: 'Line 2',
    status: 'Alarm',
    utilization: 45,
    utilizationTrend: 'down',
    cycleTime: 0,
    cycleTimeDelta: 0,
    shotCount: 567,
    condition: 'Emergency Stop',
    mold: 'M-2024-002',
    pinned: false,
    lastAlarm: 'Hydraulic pressure low',
    alarmTime: 'Active',
    dataAge: 1.8,
    setpointsChanged: false
  },
  {
    id: 'M004',
    name: 'Injection Molding #4',
    site: 'Site B', 
    line: 'Line 1',
    status: 'Maintenance',
    utilization: 0,
    utilizationTrend: 'down',
    cycleTime: 0,
    cycleTimeDelta: 0,
    shotCount: 2134,
    condition: 'Scheduled Maintenance',
    mold: 'M-2024-004',
    pinned: true,
    lastAlarm: 'Planned maintenance',
    alarmTime: '30m ago',
    dataAge: 5.2,
    setpointsChanged: false
  },
  {
    id: 'M005',
    name: 'Injection Molding #5',
    site: 'Site B',
    line: 'Line 2', 
    status: 'Running',
    utilization: 92,
    utilizationTrend: 'up',
    cycleTime: 11.8,
    cycleTimeDelta: -0.2,
    shotCount: 1567,
    condition: 'Optimized Cycle',
    mold: 'M-2024-005',
    pinned: false,
    lastAlarm: null,
    alarmTime: null,
    dataAge: 1.5,
    setpointsChanged: true
  },
  {
    id: 'M006',
    name: 'Injection Molding #6',
    site: 'Site B',
    line: 'Line 2',
    status: 'Running',
    utilization: 78,
    utilizationTrend: 'up',
    cycleTime: 13.1,
    cycleTimeDelta: 0.3,
    shotCount: 998,
    condition: 'Standard Cycle',
    mold: 'M-2024-006',
    pinned: false,
    lastAlarm: 'Quality check required',
    alarmTime: '45m ago',
    dataAge: 2.8,
    setpointsChanged: false
  }
];

// Generate mock sparkline data
export const generateSparklineData = () => Array.from({ length: 60 }, (_, i) => ({
  time: i,
  cycleTime: 12 + Math.sin(i / 10) * 2 + Math.random() * 0.5,
  shotRate: 4.8 + Math.sin(i / 8) * 0.3 + Math.random() * 0.2
}));